version: "3"

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vladglebovv
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=maison_dev
  web:
    build: 
      context: .
    command: python3 "myshop3/manage.py" runserver 0.0.0.0:8000
    volumes:
      - .:/myshop3
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
